name: UniversalInbox
options:
  bundleIdPrefix: com.universalinbox
targets:
  UniversalInbox_iOS:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources: [Sources]
    settings:
      base:
        PRODUCT_NAME: UniversalInbox
        SWIFT_VERSION: 5.0
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        TARGETED_DEVICE_FAMILY: 1,2
  
  UniversalInbox_macOS:
    type: application
    platform: macOS
    deploymentTarget: 14.0
    sources: [Sources]
    settings:
      base:
        PRODUCT_NAME: UniversalInbox
        SWIFT_VERSION: 5.0
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
